// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/balance": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回当前 API Key 对应账户的剩余余额，1 CNY = 1,000,000 credits。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询账户余额",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "balance_cny": {
                                    "type": "number"
                                },
                                "balance_credits": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/channels": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "登录用户可看到其分组专属价（group_price）；请将 routing_model 填入请求的 model 字段进行加载均衡路由。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取渠道列表并查询价格",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "channels": {
                                    "type": "array",
                                    "items": {
                                        "type": "object"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/audio": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "异步任务，提交后返回 task_id；通过 GET /v1/tasks/:id 轮询结果。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "媒体生成"
                ],
                "summary": "创建音频生成（TTS）任务",
                "parameters": [
                    {
                        "description": "音频生成参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AudioRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "任务已接受",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "task_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "发送 OpenAI 格式对话请求，支持流式（SSE）和非流式；将 model 字段填写渠道的 routing_model，服务端自动路由到真实上游模型。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM"
                ],
                "summary": "OpenAI 兼容对话（Chat Completions）",
                "parameters": [
                    {
                        "description": "请求体，参考 OpenAI Chat Completions API；model 填渠道名称（routing_model）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OpenAI 格式响应；stream=true 时为 SSE 流",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "503": {
                        "description": "无可用渠道",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/gemini": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "发送 Gemini generateContent 格式请求；model 填渠道的 routing_model（可省略，由 channel_id 指定）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM"
                ],
                "summary": "Google Gemini 原生对话",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "渠道 ID（兼容旧版）",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "description": "Gemini generateContent 请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Gemini 格式响应",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "异步任务，提交后返回 task_id；通过 GET /v1/tasks/:id 轮询结果。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "媒体生成"
                ],
                "summary": "创建图片生成任务",
                "parameters": [
                    {
                        "description": "图片生成参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ImageRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "任务已接受",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "task_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/messages": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "发送 Anthropic Messages API 格式请求，支持流式（SSE）；model 填渠道的 routing_model。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM"
                ],
                "summary": "Anthropic Claude 原生对话",
                "parameters": [
                    {
                        "description": "Claude Messages 请求体；model 填渠道名称",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Claude 格式响应；stream=true 时为 SSE 流",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/music": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "异步任务，每次生成 2 首；提交后返回 task_id，通过 GET /v1/tasks/:id 轮询结果（items 数组）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "媒体生成"
                ],
                "summary": "创建音乐生成任务（Suno）",
                "parameters": [
                    {
                        "description": "Suno 音乐生成参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MusicRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "任务已接受",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "task_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/tasks": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页获取当前 API Key 对应用户的历史任务。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "查询任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（默认 1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数（默认 20，最大 100）",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态过滤：pending/processing/done/failed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务类型过滤：image/video/audio/music",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "按 task_id 精确查询",
                        "name": "task_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间起（2006-01-02 15:04:05）",
                        "name": "start_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间止",
                        "name": "end_at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "tasks": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.TaskResult"
                                    }
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "轮询图片/视频/音频/音乐任务结果。code=150 进行中，200 成功，500 失败。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "查询任务结果",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TaskResult"
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/v1/video": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "异步任务，提交后返回 task_id；通过 GET /v1/tasks/:id 轮询结果。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "媒体生成"
                ],
                "summary": "创建视频生成任务",
                "parameters": [
                    {
                        "description": "视频生成参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VideoRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "任务已接受",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "task_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "402": {
                        "description": "余额不足",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AudioRequest": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "duration": {
                    "description": "秒，计费用",
                    "type": "integer"
                },
                "input": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "voice": {
                    "type": "string"
                }
            }
        },
        "model.ImageRequest": {
            "type": "object",
            "required": [
                "model",
                "prompt"
            ],
            "properties": {
                "aspect_ratio": {
                    "description": "宽高比，如 \"16:9\"、\"9:16\"、\"1:1\"，留空默认 1:1",
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "n": {
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "refer_images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size": {
                    "description": "分辨率档位：\"1k\"/\"2k\"/\"3k\"/\"4k\"，与 AspectRatio 共同决定最终宽高",
                    "type": "string"
                }
            }
        },
        "model.JSON": {
            "type": "object",
            "additionalProperties": true
        },
        "model.MusicRequest": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "callback_url": {
                    "description": "任务状态回调 URL（可选）",
                    "type": "string"
                },
                "continue_at": {
                    "description": "续写起始时间（秒）",
                    "type": "string"
                },
                "continue_clip_id": {
                    "description": "续写 clipId 或音频 URL",
                    "type": "string"
                },
                "cover_clip_id": {
                    "description": "cover 参考音频 URL",
                    "type": "string"
                },
                "gpt_description_prompt": {
                    "description": "灵感模式提示词（InputType=10）",
                    "type": "string"
                },
                "input_type": {
                    "description": "\"10\"=灵感模式, \"20\"=自定义模式",
                    "type": "string"
                },
                "make_instrumental": {
                    "description": "是否纯音乐，bool 或 \"true\"/\"false\""
                },
                "metadata_params": {
                    "description": "underpainting/overpainting 附加参数",
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "type": "string"
                },
                "mv_version": {
                    "description": "chirp-v5, chirp-v4-5+, chirp-v4-5, chirp-v4, chirp-v3-5",
                    "type": "string"
                },
                "prompt": {
                    "description": "歌词内容（InputType=20）",
                    "type": "string"
                },
                "tags": {
                    "description": "音乐风格，如 \"pop,female voice\"",
                    "type": "string"
                },
                "task": {
                    "description": "特殊任务类型：underpainting / overpainting",
                    "type": "string"
                },
                "title": {
                    "description": "歌曲名称",
                    "type": "string"
                }
            }
        },
        "model.TaskResult": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "integer"
                },
                "code": {
                    "type": "integer"
                },
                "credits_charged": {
                    "type": "integer"
                },
                "items": {
                    "description": "生成结果列表（多结果任务，如音乐每次返回两首）",
                    "type": "array",
                    "items": {}
                },
                "msg": {
                    "description": "状态描述或错误信息",
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/model.JSON"
                },
                "result": {
                    "$ref": "#/definitions/model.JSON"
                },
                "status": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "task_type": {
                    "type": "string"
                },
                "upstream_task_id": {
                    "type": "string"
                },
                "url": {
                    "description": "生成结果 URL（成功时，单结果任务）",
                    "type": "string"
                }
            }
        },
        "model.VideoRequest": {
            "type": "object",
            "required": [
                "model",
                "prompt"
            ],
            "properties": {
                "aspect_ratio": {
                    "description": "宽高比，如 \"16:9\"（横屏）、\"9:16\"（竖屏），留空默认 16:9",
                    "type": "string"
                },
                "duration": {
                    "description": "时长秒数字符串，如 \"5\"",
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                },
                "refer_images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size": {
                    "description": "分辨率档位：\"720p\"/\"1080p\"/\"2k\"/\"4k\"，与 AspectRatio 共同决定宽高",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "FanAPI",
	Description:      "LLM 对话 · 图片 / 视频 / 音频生成 · 任务查询",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
